---
abstract: 'Shared code for things that communicate data about dzil roles.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Util-RoleDB
provides:
  Dist::Zilla::Util::RoleDB:
    file: lib/Dist/Zilla/Util/RoleDB.pm
    version: '0.004001'
  Dist::Zilla::Util::RoleDB::Entry:
    file: lib/Dist/Zilla/Util/RoleDB/Entry.pm
    version: '0.004001'
  Dist::Zilla::Util::RoleDB::Entry::Phase:
    file: lib/Dist/Zilla/Util/RoleDB/Entry/Phase.pm
    version: '0.004001'
  Dist::Zilla::Util::RoleDB::Items:
    file: lib/Dist/Zilla/Util/RoleDB/Items.pm
    version: '0.004001'
  Dist::Zilla::Util::RoleDB::Items::Core:
    file: lib/Dist/Zilla/Util/RoleDB/Items/Core.pm
    version: '0.004001'
  Dist::Zilla::Util::RoleDB::Items::ThirdParty:
    file: lib/Dist/Zilla/Util/RoleDB/Items/ThirdParty.pm
    version: '0.004001'
recommends:
  Moo: '1.000008'
requires:
  Carp: '0'
  Module::Runtime: '0'
  Moo: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Util-RoleDB/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Util-RoleDB
  repository: https://github.com/kentnl/Dist-Zilla-Util-RoleDB.git
version: '0.004001'
